Repository primefaces-extensions/primefaces-extensions, pull requests merged in 2024-08, with the labels that each got.

#1630 [QRcode] Label attributes can now be updated
  core/src/main/java/org/primefaces/extensions/component/qrcode/QRCode.java
  core/src/main/java/org/primefaces/extensions/component/qrcode/QRCodeRenderer.java
  core/src/main/resources/META-INF/primefaces-extensions.taglib.xml
Labels: defect

#1632 Fix #1631: DocViewer add warning if HIDE_RESOURCE_VERSION is enabled
  core/src/main/java/org/primefaces/extensions/component/documentviewer/DocumentViewerRenderer.java
Labels: defect

#1636 SunEditor 2.47.0
  core/src/main/resources/META-INF/resources/primefaces-extensions/suneditor/0-suneditor.min.css
  core/src/main/resources/META-INF/resources/primefaces-extensions/suneditor/0-suneditor.min.js
Labels: dependencies

#1640 Fix #1639: SunEditor do not escape value
  core/src/main/java/org/primefaces/extensions/component/suneditor/SunEditorRenderer.java
Labels: defect

#1665 Fix #1652: zxing 0.21.3
  core/src/main/resources/META-INF/resources/primefaces-extensions/codescanner/zxing.min.js
Labels: dependencies, javascript
