Repository primefaces-extensions/primefaces-extensions, pull requests merged in 2024-05, with the labels that each got.

#1541 #1540 : Allow custom morphia FindOptions/CountOptions
  core/src/main/java/org/primefaces/extensions/model/mongo/MorphiaLazyDataModel.java
Labels: enhancement

#1548 Allow both URN and URI Taglib
  core/pom.xml
Labels: enhancement

#1552 Fix #1551: InputPlace zindex in dialogs
  core/pom.xml
  core/src/main/resources/META-INF/resources/primefaces-extensions/inputplace/inputplace-widget.js
  monacoeditor/pom.xml
  pom.xml
  showcase/pom.xml
Labels: defect

#1556 Fix #128: Creates an Open Steet Map Component
  core/src/main/java/org/primefaces/extensions/component/osmap/OSMap.java
  core/src/main/java/org/primefaces/extensions/component/osmap/OSMapBase.java
  core/src/main/java/org/primefaces/extensions/component/osmap/OSMapRenderer.java
  core/src/main/resources/META-INF/faces-config.xml
  core/src/main/resources/META-INF/primefaces-extensions.taglib.xml
  core/src/main/resources/META-INF/resources/primefaces-extensions/leaflet/images/layers-2x.png
  core/src/main/resources/META-INF/resources/primefaces-extensions/leaflet/images/layers.png
  core/src/main/resources/META-INF/resources/primefaces-extensions/leaflet/images/marker-icon-2x.png
  core/src/main/resources/META-INF/resources/primefaces-extensions/leaflet/images/marker-icon.png
  core/src/main/resources/META-INF/resources/primefaces-extensions/leaflet/images/marker-shadow.png
  core/src/main/resources/META-INF/resources/primefaces-extensions/leaflet/leaflet.css
  core/src/main/resources/META-INF/resources/primefaces-extensions/leaflet/leaflet.js
  core/src/main/resources/META-INF/resources/primefaces-extensions/osmap/osmap.js
Labels: :game_die: new component
