Repository primefaces-extensions/primefaces-extensions, pull requests merged in 2024-03, with the labels that each got.

#1460 Fix #1459: SunEditor prevent HTML manipulation
  core/src/main/resources/META-INF/resources/primefaces-extensions/suneditor/1-suneditor-widget.js
Labels: enhancement

#1462 Fix #1459: 13.0.8 SunEditor prevent HTML manipulation
  core/src/main/resources/META-INF/resources/primefaces-extensions/suneditor/1-suneditor-widget.js
Labels: enhancement

#1465 Fix #1464: 13.0.8 DocumentViewer fallback to download value
  core/src/main/java/org/primefaces/extensions/component/documentviewer/DocumentViewerRenderer.java
Labels: defect

#1466 Fix #1464: DocumentViewer fallback to download value
  core/src/main/java/org/primefaces/extensions/component/documentviewer/DocumentViewerRenderer.java
Labels: defect

#1455 new InputOtp component
  core/pom.xml
  core/src/main/java/org/primefaces/extensions/component/inputotp/InputOtp.java
  core/src/main/java/org/primefaces/extensions/component/inputotp/InputOtpRenderer.java
  core/src/main/java/org/primefaces/extensions/util/ExtLangUtils.java
  core/src/main/resources/META-INF/faces-config.xml
  core/src/main/resources/META-INF/primefaces-extensions.taglib.xml
  core/src/main/resources/META-INF/resources/primefaces-extensions/inputotp/inputotp-widget.js
  core/src/main/resources/META-INF/resources/primefaces-extensions/inputotp/inputotp.css
  showcase/pom.xml
  showcase/src/main/java/org/primefaces/extensions/showcase/controller/inputotp/BasicInputOtpController.java
  showcase/src/main/webapp/sections/inputotp/basicUsage.xhtml
  showcase/src/main/webapp/sections/inputotp/example-basicUsage.xhtml
  showcase/src/main/webapp/sections/inputotp/useCasesChoice.xhtml
  showcase/src/main/webapp/templates/showcaseLayout.xhtml
  showcase/src/main/webapp/views/inputotp.xhtml
Labels: :game_die: new component

#1481 InputPhone: wrap input event
  core/src/main/resources/META-INF/resources/primefaces-extensions/inputphone/inputphone-widget.js
Labels: defect

#1483 Fix #1482: InputPhone inputStyleClass
  core/src/main/java/org/primefaces/extensions/component/inputphone/InputPhoneRenderer.java
Labels: defect

#1479 Fix #137: InputPlace component
  core/pom.xml
  core/src/main/java/org/primefaces/extensions/component/inputphone/InputPhoneRenderer.java
  core/src/main/java/org/primefaces/extensions/component/inputplace/InputPlace.java
  core/src/main/java/org/primefaces/extensions/component/inputplace/InputPlaceRenderer.java
  core/src/main/java/org/primefaces/extensions/model/inputplace/Place.java
  core/src/main/resources/META-INF/faces-config.xml
  core/src/main/resources/META-INF/primefaces-extensions.taglib.xml
  core/src/main/resources/META-INF/resources/primefaces-extensions/inputplace/inputplace-widget.js
  showcase/pom.xml
  showcase/src/main/java/org/primefaces/extensions/showcase/controller/inputplace/BasicInputPlaceController.java
  showcase/src/main/webapp/resources/images/inputplace.png
  showcase/src/main/webapp/sections/inputplace/basicUsage.xhtml
  showcase/src/main/webapp/sections/inputplace/example-basicUsage.xhtml
  showcase/src/main/webapp/sections/inputplace/example-mapUsage.xhtml
  showcase/src/main/webapp/sections/inputplace/mapUsage.xhtml
  showcase/src/main/webapp/sections/inputplace/useCasesChoice.xhtml
  showcase/src/main/webapp/templates/showcaseLayout.xhtml
  showcase/src/main/webapp/views/inputplace.xhtml
Labels: :game_die: new component

#1494 Fix #1487: Refactor JS/CSS compression
  core/pom.xml
Labels: enhancement

#1499 update to International Telephone Input 20.1.0
  core/src/main/resources/META-INF/resources/primefaces-extensions/inputphone/inputphone-widget.js
  core/src/main/resources/META-INF/resources/primefaces-extensions/inputphone/intlTelInput.css
  core/src/main/resources/META-INF/resources/primefaces-extensions/inputphone/intlTelInput.js
  core/src/main/resources/META-INF/resources/primefaces-extensions/inputphone/utils.js
Labels: dependencies, javascript

#1504 Fix #1502: 13.0.8 SunEditor fix link editor in dialog
  core/src/main/resources/META-INF/resources/primefaces-extensions/suneditor/1-suneditor-widget.js
Labels: defect

#1503 Fix #1502: SunEditor fix link editor in dialog
  core/src/main/resources/META-INF/resources/primefaces-extensions/suneditor/1-suneditor-widget.js
Labels: defect

#1506 InputOtp: add separator facet and customization example
  core/src/main/java/org/primefaces/extensions/component/inputotp/InputOtp.java
  core/src/main/java/org/primefaces/extensions/component/inputotp/InputOtpRenderer.java
  showcase/src/main/webapp/sections/inputotp/customization.xhtml
  showcase/src/main/webapp/sections/inputotp/example-customization.xhtml
  showcase/src/main/webapp/sections/inputotp/useCasesChoice.xhtml
Labels: enhancement
